config/routes.rb
FbEvents::Application.routes.draw do
  resources :categories

  get "home/index"

  root 'home#index'
  get "home/map"
  post "home/add"
  post "home/search"
  get 'events', :controller => 'events', :action => 'show'
  get 'markers', :controller => 'home', :action => 'markers'
  get 'clean', :controller => 'home', :action => 'clean'
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy', as: 'signout'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new
    @category.name = category_params['name']

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def show
		@events = Event.find(:all)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cats = Category.find(:all)

  end

  def map
    @cats = Category.find(:all)
    render(:locals => {:data => "/markers.xml"}) 
  end

  def markers
    respond_to do |format|
      search_category = session[:search_category]
      search_lat = session[:search_lat]
      search_lon = session[:search_lon]
      search_distance = session[:search_distance]

      @markers = Event.all
      if search_category != nil
        #markers filtering by category
        @markers = Event.where(category_id: search_category)
        #markers filtering by distance from point
        if (search_lat != nil) && (search_lon != nil) && (search_distance != nil)
          filtered_markers = []

          @markers.each do |marker|
            if is_in_region(marker.lat, marker.lon, search_lat, search_lon, search_distance)
              filtered_markers += [marker]
            end
          end
          @markers = filtered_markers
        end
      end
      
      format.xml { render :xml => @markers.to_xml( :only => [:attending, :event_id, :title, :lat, :lon, :description]) }
      format.json { render :json => @markers.to_json( :only => [:attending, :event_id, :title, :lat, :lon, :description]) }
    end
  end

  def clean
    @events = Event.find(:all)
    for event in @events
      event.destroy
    end

    redirect_to "/home/map/"
  end

  def search
    require 'geocoder'

    category_id = params[:category]
    distance = params[:range][0].to_i

    address = params[:search_address][0]

    if (address!="")
      request_url = URI.escape("http://maps.googleapis.com/maps/api/geocode/json?address=#{address}&sensor=true")
      address_results = JSON.parse(open(request_url).read)

      puts "--- GEOC TEST ----"
      city = request.ip
      puts city

      if(address_results['status'] == 'OK')
        puts "---------- GEOCODER ----------"
        puts request_url
        puts address_results['results'][0]['geometry']['location']['lat']

        session[:search_category] = category_id
        session[:search_lat] = address_results['results'][0]['geometry']['location']['lat']
        session[:search_lon] = address_results['results'][0]['geometry']['location']['lng']
        session[:search_distance] = distance
      else
        flash[:error] = "Address not found!"
        session[:search_lat] = nil
        session[:search_lon] = nil
        session[:search_distance] = nil
      end
    else
      session[:search_lat] = nil
      session[:search_lon] = nil
      session[:search_distance] = nil
    end
    redirect_to "/home/map/"
  end

  def add
  	require 'open-uri'
    require 'json'

    app_id = '1381006338788358'
    secret_id = '6aa740712042ad5e527395ac7a515ea0'
    access_token_url = "https://graph.facebook.com/oauth/access_token?client_id=#{app_id}&client_secret=#{secret_id}&grant_type=client_credentials"
    access_token_parts = (open(access_token_url).read).split("=")
    access_token = access_token_parts[1]

    event_id = params[:event_id][0]
    category_id = params[:category1]

    members_url = URI.escape("https://graph.facebook.com/#{event_id}/attending?access_token=#{access_token}")
    members_result = JSON.parse(open(members_url).read)

    event_data_url = URI.escape("https://graph.facebook.com/#{event_id}?access_token=#{access_token}")
    event_data_result = JSON.parse(open(event_data_url).read)

  	@event = Event.new
    @event.event_id = event_id
  	@event.title = event_data_result['name']
  	@event.owner = event_data_result['owner']['name']
  	@event.description = event_data_result['description']
  	@event.lat = event_data_result['venue']['latitude']
  	@event.lon = event_data_result['venue']['longitude']
  	@event.attending = members_result['data'].count
    @event.category_id = category_id
  	@event.save
  	redirect_to "/home/map/"
  end

  RAD_PER_DEG = 0.017453293  #  PI/180
  Rkm = 6371
  def is_in_region( lat1, lon1, lat2, lon2, distance )
    

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    dlon_rad = dlon * RAD_PER_DEG 
    dlat_rad = dlat * RAD_PER_DEG

    lat1_rad = lat1 * RAD_PER_DEG
    lon1_rad = lon1 * RAD_PER_DEG

    lat2_rad = lat2 * RAD_PER_DEG
    lon2_rad = lon2 * RAD_PER_DEG


    a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
    c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

    dKm = Rkm * c
    puts "---- DISTANCE ----"
    puts dKm

    if dKm > distance
      return false
    else
      return true
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/events/show.html.erb
<html>
<head>
</head>
<body>
<table>
<tr><td>ID</td><td>title</td><td>category</td><td>description</td><td>owner</td><td>lat</td><td>lon</td><td>attendings</td></tr>

<% for event in @events %>
	<tr>
		<td><%= event.event_id %></td>
		<td><%= event.title %></td>
		<td><%= event.category.name %></td>
		<td><%= event.description %></td>
		<td><%= event.owner %></td>
		<td><%= event.lat %></td>
		<td><%= event.lon %></td>
		<td><%= event.attending %></td>
	</tr>
<% end %>

</table>
</body>
</html>

app/views/home/index.html.erb
<section role="main">
	<div class="row ">
		<div class="main-page-content small-9 small-centered columns">
			<div class="row map-bg">
				<div class="small-8 columns">
					<h4>Search Popular Event from Facebook </br>
					By Category </br>
					By Place </br>
					By Date	</br>				
					In Range </br>
					Be updated ! </h4>					
					
				</div>				
			</div>
		</div>		
	</div>
	<div class="row">
		<div class="large-3 medium-6 small-9 large-centered small-centered columns">
			<%= link_to "Get Started !", home_map_path, class:'button', 'data-no-turbolink' => true%>
		</div>
	</div>
	
</section>

app/views/home/map.html.erb
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBxiRAus5G-hfo7sqR_0FrR1ZRFMIOUIY&sensor=false">
    </script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script type="text/javascript" src="/assets/underscore-min.js"></script>
<script>
  //var LAT = <%= session[:search_lat] %>;
  //var LON = <%= session[:search_lon] %>;
</script>

<% if flash[:error] %>
  <div class="geo-error">
    <div class="message">
      <div class="close-btn"> x </div>
      <p><%= flash[:error] %></p></div>
  </div>
<% end %>
<div class="section-container auto" data-section>
  <section class="active">
    <p class="title" data-section-title><a href="#panel1">Map</a></p>
    <div class="content" data-section-content>
     
      <div id='map' data-section-content> </div>
    </div>
  </section>
  <!-- ======================== Search section =================== -->
  <section>
    <p class="title" data-section-title><a href="#panel3"> Search</a></p>
    <div class="content" data-section-content>
      <h3> Specify your criteria: </h3>
      <div class="row">
        <div class="large-4 columns">
        <%= form_tag({controller: "home", action: "search"} , method: "post") do %>
          <label for="category"><h6> Category </h6></label>
          <%= select_tag("category", 
            options_from_collection_for_select(@cats, 'id', 'name')) %>
          <label for="search-date"><h6> Date </h6> </label>
          <div class="search_datepicker">
            <input type="text" class="span2" value="" data-date-format="dd/mm/yyyy" id="search-date">
           </div>

          <label for="search_event"><h6> Search Address </h6></label>
          <%= text_field 'search_address', nil, :placeholder => 'Enter adress...' %> 
          <label for="range"><h6> Radius </h6></label>
          <%= text_field 'range', nil, :placeholder => 'Specify range (km)' %>
          <div class="small-2">
            <%= submit_tag("Search", class:"button ") %>
          </div>
        <% end %>
        </div>

      </div>
    </div>
  </section>
    <!-- ======================== Add section =================== -->

  <section>
    <p class="title" data-section-title><a href="#panel2">Add</a></p>
    <div class="content" data-section-content>
      <div class="row add-form-slider">        
        <div class="add-form-content"> 
          <!-- <div class=" large- columns"> -->
            <%= form_tag({controller: "home", action: "add"} , method: "post") do %>
              <h3> Add Event </h3>
              <div class="row collapse">
                <div class="small-10 columns">
                  <%= text_field 'event_id', nil, :placeholder => 'Enter facebook event id here...' %> 
                  <label for="category1"> Category </label>
                  <%= select_tag("category1", 
                    options_from_collection_for_select(@cats, 'id', 'name')) %>
                </div>
                <div class="small-2 columns">
                  <%= submit_tag("Add", class:"button prefix") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- 
<div class="row add-form-slider">
  <div class="add-form-icon">
    <p> + </p>
  </div>
  <div class="add-form-content"> 
      <%= form_tag({controller: "home", action: "add"} , method: "post") do %>
      	<h3> Add Event </h3>
        <div class="row collapse">
          <div class="small-10 columns">
            <%= text_field 'event_id', nil, :placeholder => 'Enter facebook event id here...' %> 
          </div>
          <div class="small-2 columns">
            <%= submit_tag("Add", class:"button prefix") %>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>
<div id='map' > </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<nav class="top-bar">
  		<ul class="title-area">
    	<!-- Title Area -->
    		<li class="name">
     			<h1><%= link_to "FB events", home_index_path %></h1>
    		</li>
    		<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		  </ul>

  		<section class="top-bar-section">
  			<ul class="right">
				<li class="name">
          
          <div>
		<h1>
            <% if current_user %>
              Welcome <strong><%= current_user.name %></strong>! fkkk
            <%= link_to "Sign out", signout_path, id: "sign_out" %>
            <% else %>
            <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", :target => :blank %>
            <% end %>
</h1>
          </div>
        
        </li>
				<li class="divider"></li>
				<li><a href="#"> About </a></li>
  			</ul>
		</section>
  	</nav>

    <%= yield %>

    <%= javascript_include_tag "application" %>

  </body>
</html>